# ---
# jupyter:
#   jupytext:
#     formats: py:percent,ipynb
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Lab 05: The $1 Pretraining Run
#
# **Act IV — How They Learn** | GPU recommended | ~90–120 minutes
#
# ---
#
# ### What you will learn
#
# 1. **Build** a 10.7M-parameter GPT-2 model from scratch — and understand
#    where each of those 10.7 million parameters lives
# 2. **Train** it on TinyStories, a dataset of synthetic children's stories
#    used in real language model research (Eldan & Li, 2023)
# 3. **Watch** the loss curve descend from random noise (loss ~9.2) to
#    coherent language (loss ~2.5) in minutes
# 4. **Test the textbook hypothesis**: train a second model on corrupted
#    data and see, from your own experiment, that data quality beats
#    data quantity
# 5. **Generate** text from both models and compare the results
#
# ---
#
# ### The idea
#
# Everyone talks about pretraining, but very few people have actually done it.
# Today you will. Not on a 7B model with a cluster — on a tiny model with
# your laptop. The architecture is real (GPT-2 style), the data is real
# (TinyStories), and the training dynamics are real (the loss curve, the
# learning rate schedule, the generation quality). The only thing that is
# small is the scale.
#
# By the end you will own two trained language models and a measured answer
# to the question: "Does data quality matter more than data quantity?"

# %% [markdown]
# ---
# ## 1. Setup

# %%
import subprocess
import sys

try:
    import microscale
except ImportError:
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", "git+https://github.com/user/Microscale.git"]
    )
    import microscale

from microscale import apply_style, device_summary, get_torch_device, is_ci, show

apply_style()
device = get_torch_device()
print(device_summary())

# %%
import os
import time

import matplotlib.pyplot as plt
import numpy as np
import torch
from rich.console import Console
from rich.progress import BarColumn, Progress, TextColumn, TimeRemainingColumn
from rich.table import Table

console = Console()

# %% [markdown]
# ---
# ## 2. Build the Model
#
# Our model is a standard GPT-2 architecture: token embeddings + position
# embeddings → stack of transformer blocks → language model head. The key
# config choices that give us ~10.7M parameters:
#
# | Config | Value | Why |
# |--------|-------|-----|
# | Vocabulary | 10,000 tokens | Keeps embedding table small |
# | Hidden dim | 320 | Narrow but deep |
# | Heads | 5 | 64 dim per head |
# | Layers | 6 | Enough depth for basic patterns |
# | FFN dim | 1,280 | Standard 4x expansion |
# | Context | 512 tokens | Fits a full TinyStory |
# | Tied weights | Yes | Output head reuses embeddings |

# %%
from microscale.tiny_gpt import TinyGPT

model = TinyGPT(
    vocab_size=10000,
    d_model=320,
    n_heads=5,
    n_layers=6,
    d_ff=1280,
    max_seq_len=512,
    tie_weights=True,
).to(device)

n_params = model.count_parameters()
console.print(f"\n  Model: [bold]{n_params:,}[/bold] trainable parameters")

# Parameter breakdown
table = Table(title="Parameter Budget")
table.add_column("Component", style="bold")
table.add_column("Parameters", justify="right")
table.add_column("Fraction", justify="right")

components = {
    "Token embeddings": model.tok_emb.weight.numel(),
    "Position embeddings": model.pos_emb.weight.numel(),
    "Attention (all layers)": sum(
        p.numel() for block in model.blocks for name, p in block.attn.named_parameters()
    ),
    "FFN (all layers)": sum(
        p.numel() for block in model.blocks for name, p in block.ffn.named_parameters()
    ),
    "LayerNorms": sum(
        p.numel() for block in model.blocks for name, p in block.named_parameters() if "ln" in name
    )
    + model.ln_f.weight.numel()
    + model.ln_f.bias.numel(),
    "Output head": 0,  # tied with embeddings
}

for comp, count in components.items():
    table.add_row(comp, f"{count:,}", f"{count / n_params:.1%}")
console.print(table)

# %% [markdown]
# ---
# ## 3. Prepare the Data
#
# **TinyStories** is a dataset of ~2.1 million short children's stories
# generated by GPT-3.5 and GPT-4 (Eldan & Li, 2023, Microsoft Research).
# Stories use simple vocabulary that a 3-4 year old would understand, but
# have correct grammar, coherent plots, and consistent characters.
#
# We use a restricted vocabulary of 10,000 tokens built from the GPT-2
# tokenizer — keeping only the most frequent tokens. This matches the
# approach from the original TinyStories paper.

# %%
from datasets import load_dataset
from transformers import AutoTokenizer

print("Loading TinyStories dataset (streaming)...")
raw_dataset = load_dataset("roneneldan/TinyStories", split="train", streaming=True)

# Use GPT-2 tokenizer but we'll only keep tokens in our vocab range
base_tokenizer = AutoTokenizer.from_pretrained("gpt2")
if base_tokenizer.pad_token is None:
    base_tokenizer.pad_token = base_tokenizer.eos_token

VOCAB_SIZE = 10000
SEQ_LEN = 512

# %% [markdown]
# We need to convert stories into fixed-length token sequences. Stories that
# are longer than 512 tokens get truncated; shorter ones get packed together.

# %%


def tokenize_and_chunk(dataset, num_tokens: int, seq_len: int = 512):
    """Tokenize stories and pack into fixed-length chunks."""
    all_tokens = []
    token_count = 0

    for example in dataset:
        tokens = base_tokenizer.encode(example["text"])
        # Clamp to our restricted vocab
        tokens = [t if t < VOCAB_SIZE else 0 for t in tokens]
        all_tokens.extend(tokens)
        token_count += len(tokens)
        if token_count >= num_tokens:
            break

    # Pack into fixed-length sequences
    all_tokens = all_tokens[: (len(all_tokens) // seq_len) * seq_len]
    sequences = torch.tensor(all_tokens, dtype=torch.long).view(-1, seq_len)
    return sequences


# How many tokens to use (reduce in CI)
TOTAL_TOKENS = 500_000 if is_ci() else 8_000_000

console.print(f"\n  Tokenizing {TOTAL_TOKENS:,} tokens from TinyStories...")
clean_data = tokenize_and_chunk(raw_dataset, num_tokens=TOTAL_TOKENS)
console.print(f"  Created [bold]{clean_data.shape[0]:,}[/bold] sequences of length {SEQ_LEN}")

# %% [markdown]
# ---
# ## 4. Create Corrupted Data
#
# To test the textbook hypothesis, we create a corrupted version of the
# same data. Same number of tokens, same vocabulary — but the quality
# is deliberately degraded:
#
# - **Shuffled sentences**: Break stories into sentences and randomize order
# - **Duplicated content**: Repeat 30% of stories, displacing unique content
# - **Random noise**: Replace 5% of tokens with random vocabulary items
#
# This simulates the difference between curated "textbook" data and noisy
# web-crawled data.

# %%


def corrupt_data(sequences: torch.Tensor, seed: int = 42) -> torch.Tensor:
    """Create a corrupted version of the training data."""
    rng = np.random.RandomState(seed)
    corrupted = sequences.clone()
    n_seqs = corrupted.shape[0]

    # 1. Shuffle token order within 30% of sequences (destroys coherence)
    shuffle_mask = rng.random(n_seqs) < 0.3
    for i in np.where(shuffle_mask)[0]:
        perm = torch.randperm(SEQ_LEN)
        corrupted[i] = corrupted[i][perm]

    # 2. Duplicate 30% of sequences (displacing unique content)
    n_dup = int(n_seqs * 0.3)
    dup_sources = rng.choice(n_seqs, n_dup)
    dup_targets = rng.choice(n_seqs, n_dup, replace=False)
    for src, tgt in zip(dup_sources, dup_targets):
        corrupted[tgt] = corrupted[src]

    # 3. Replace 5% of tokens with random tokens
    noise_mask = torch.tensor(
        rng.random(corrupted.shape) < 0.05,
    )
    random_tokens = torch.randint(0, VOCAB_SIZE, corrupted.shape)
    corrupted[noise_mask] = random_tokens[noise_mask]

    return corrupted


corrupted_data = corrupt_data(clean_data)
console.print(f"  Created corrupted dataset: {corrupted_data.shape[0]:,} sequences")

# %% [markdown]
# ---
# ## 5. The Training Loop
#
# Now we train two identical models — same architecture, same hyperparameters,
# same number of training steps — but on different data.

# %%
BATCH_SIZE = 32 if not is_ci() else 8
N_STEPS = 2000 if not is_ci() else 100
LR = 5e-4
WARMUP_STEPS = 200 if not is_ci() else 10
LOG_EVERY = 50 if not is_ci() else 10


def train_model(
    name: str,
    data: torch.Tensor,
    n_steps: int = N_STEPS,
) -> tuple[TinyGPT, list[float]]:
    """Train a TinyGPT model and return (model, loss_history)."""
    mdl = TinyGPT(
        vocab_size=VOCAB_SIZE,
        d_model=320,
        n_heads=5,
        n_layers=6,
        d_ff=1280,
        max_seq_len=SEQ_LEN,
    ).to(device)

    optimizer = torch.optim.AdamW(
        mdl.parameters(),
        lr=LR,
        betas=(0.9, 0.95),
        weight_decay=0.1,
    )

    # Cosine learning rate schedule with warmup
    def lr_schedule(step):
        if step < WARMUP_STEPS:
            return step / max(WARMUP_STEPS, 1)
        progress = (step - WARMUP_STEPS) / max(n_steps - WARMUP_STEPS, 1)
        return 0.5 * (1 + np.cos(np.pi * progress))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_schedule)

    n_seqs = data.shape[0]
    losses = []
    mdl.train()

    t0 = time.time()
    with Progress(
        TextColumn(f"[bold]{name}[/bold]"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        TimeRemainingColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Training", total=n_steps)

        for step in range(n_steps):
            # Random batch
            idx = torch.randint(0, n_seqs, (BATCH_SIZE,))
            batch = data[idx].to(device)

            output = mdl(batch, labels=batch)
            loss = output["loss"]

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(mdl.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            losses.append(loss.item())
            progress.update(task, advance=1)

    elapsed = time.time() - t0
    tokens_seen = n_steps * BATCH_SIZE * SEQ_LEN
    console.print(
        f"  {name}: {elapsed:.0f}s, "
        f"{tokens_seen:,} tokens, "
        f"final loss: [bold]{losses[-1]:.3f}[/bold]"
    )
    return mdl, losses


# %% [markdown]
# ### Train Model A: Clean Data

# %%
console.print("\n[bold]Training Model A on clean TinyStories...[/bold]\n")
model_clean, losses_clean = train_model("Clean", clean_data)

# %% [markdown]
# ### Train Model B: Corrupted Data

# %%
console.print("\n[bold]Training Model B on corrupted data...[/bold]\n")
model_corrupt, losses_corrupt = train_model("Corrupted", corrupted_data)

# %% [markdown]
# ---
# ## 6. Compare the Loss Curves
#
# This is where the textbook hypothesis becomes visible.

# %%
# Smooth losses for clearer comparison
window = max(1, len(losses_clean) // 50)


def smooth(values, w):
    return np.convolve(values, np.ones(w) / w, mode="valid")


fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# Plot 1: Full loss curves
ax = axes[0]
steps = np.arange(len(losses_clean))
ax.plot(steps, losses_clean, alpha=0.15, color="#4a7c74")
ax.plot(steps, losses_corrupt, alpha=0.15, color="#8b3a3a")
ax.plot(
    np.arange(len(smooth(losses_clean, window))),
    smooth(losses_clean, window),
    color="#4a7c74",
    linewidth=2.5,
    label="Clean data",
)
ax.plot(
    np.arange(len(smooth(losses_corrupt, window))),
    smooth(losses_corrupt, window),
    color="#8b3a3a",
    linewidth=2.5,
    label="Corrupted data",
)
ax.set_xlabel("Training Step")
ax.set_ylabel("Cross-Entropy Loss")
ax.set_title("Loss Curves: Clean vs Corrupted Data")
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)

# Plot 2: Final loss comparison
ax = axes[1]
final_clean = np.mean(losses_clean[-100:])
final_corrupt = np.mean(losses_corrupt[-100:])

bars = ax.bar(
    ["Clean Data", "Corrupted Data"],
    [final_clean, final_corrupt],
    color=["#4a7c74", "#8b3a3a"],
    width=0.5,
    edgecolor="#1a1f3a",
    linewidth=1.5,
)
for bar, val in zip(bars, [final_clean, final_corrupt]):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.05,
        f"{val:.3f}",
        ha="center",
        fontsize=13,
        fontweight="bold",
    )
ax.set_ylabel("Final Loss (lower is better)")
ax.set_title("Final Loss After Training")
ax.set_ylim(0, max(final_clean, final_corrupt) * 1.3)

fig.suptitle(
    "The Textbook Hypothesis: Data Quality Beats Data Quantity",
    fontsize=14,
    fontweight="bold",
    y=1.02,
)
fig.tight_layout()
show(fig, filename="05-loss-curves.png")

# %%
gap = final_corrupt - final_clean
pct = (gap / final_clean) * 100
console.print(f"\n  Clean final loss:     [bold green]{final_clean:.3f}[/bold green]")
console.print(f"  Corrupted final loss: [bold red]{final_corrupt:.3f}[/bold red]")
console.print(f"  Gap: [bold]{gap:.3f}[/bold] ({pct:.0f}% worse)")

# %% [markdown]
# The clean-data model reaches a lower loss in the same number of steps.
# Same architecture, same compute budget, same number of tokens — the
# only difference is data quality. This is the textbook hypothesis in
# miniature: curated data learns more efficiently than noisy data.

# %% [markdown]
# ---
# ## 7. Generate Text
#
# Let's see what these models actually produce. We will give both the
# same prompt and compare their completions.

# %%
PROMPTS = [
    "Once upon a time, there was a little",
    "The dog ran to the",
    "She was very happy because",
    "One day, a boy found a",
]


def generate_text(mdl, prompt, max_tokens=80):
    """Generate text from a prompt."""
    mdl.eval()
    tokens = base_tokenizer.encode(prompt)
    tokens = [t if t < VOCAB_SIZE else 0 for t in tokens]
    input_ids = torch.tensor([tokens], device=device)

    with torch.no_grad():
        output_ids = mdl.generate(input_ids, max_new_tokens=max_tokens)

    # Decode, handling tokens that map to our restricted vocab
    generated = output_ids[0].tolist()
    return base_tokenizer.decode(generated, skip_special_tokens=True)


# %%
console.print("\n[bold]Generation Comparison[/bold]\n")

for prompt in PROMPTS:
    console.print(f'  [bold]Prompt:[/bold] "{prompt}"\n')

    clean_text = generate_text(model_clean, prompt)
    corrupt_text = generate_text(model_corrupt, prompt)

    console.print("  [green]Clean model:[/green]")
    console.print(f"    {clean_text[:200]}\n")
    console.print("  [red]Corrupted model:[/red]")
    console.print(f"    {corrupt_text[:200]}\n")
    console.print("  " + "─" * 60 + "\n")

# %% [markdown]
# The clean-data model should produce more coherent stories with consistent
# characters and plot. The corrupted-data model will likely produce grammatical
# fragments that do not hold together — because it learned from shuffled,
# duplicated, noisy text.

# %% [markdown]
# ---
# ## 8. Visualize What the Model Learned
#
# Let's look at the learning rate schedule and the loss landscape.

# %%
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# LR schedule
ax = axes[0]
lr_values = []
for step in range(N_STEPS):
    if step < WARMUP_STEPS:
        lr_val = LR * step / max(WARMUP_STEPS, 1)
    else:
        progress = (step - WARMUP_STEPS) / max(N_STEPS - WARMUP_STEPS, 1)
        lr_val = LR * 0.5 * (1 + np.cos(np.pi * progress))
    lr_values.append(lr_val)

ax.plot(lr_values, color="#b87333", linewidth=2)
ax.set_xlabel("Training Step")
ax.set_ylabel("Learning Rate")
ax.set_title("Cosine Learning Rate Schedule with Warmup")
ax.axvline(
    WARMUP_STEPS,
    color="#6b7091",
    linestyle="--",
    alpha=0.5,
    label=f"Warmup ends (step {WARMUP_STEPS})",
)
ax.legend()
ax.grid(True, alpha=0.3)

# Loss distribution over training
ax = axes[1]
early = losses_clean[: min(200, len(losses_clean))]
late = losses_clean[max(0, len(losses_clean) - 200) :]
ax.hist(early, bins=30, alpha=0.6, color="#8b3a3a", label="First 200 steps")
ax.hist(late, bins=30, alpha=0.6, color="#4a7c74", label="Last 200 steps")
ax.set_xlabel("Loss Value")
ax.set_ylabel("Frequency")
ax.set_title("Loss Distribution: Early vs Late Training")
ax.legend()
ax.grid(True, alpha=0.3)

fig.suptitle(
    "Training Dynamics",
    fontsize=13,
    fontweight="bold",
    y=1.02,
)
fig.tight_layout()
show(fig, filename="05-training-dynamics.png")

# %% [markdown]
# ---
# ## 9. Save Your Models
#
# You now own two trained language models. Let's save them.

# %%
from microscale.viz import _output_dir

output_path = _output_dir()
torch.save(model_clean.state_dict(), output_path / "05-model-clean.pt")
torch.save(model_corrupt.state_dict(), output_path / "05-model-corrupted.pt")

clean_size = os.path.getsize(output_path / "05-model-clean.pt") / 1e6
console.print("\n  Saved models to outputs/")
console.print(f"  Model size: {clean_size:.1f} MB each")
console.print(f"  Total training tokens: {N_STEPS * BATCH_SIZE * SEQ_LEN:,}")

# %% [markdown]
# ---
# ## What You Learned
#
# | Finding | Evidence |
# |---|---|
# | You can train a real LM on a laptop | 10.7M params, ~10 min |
# | Loss starts at ln(vocab) | ~9.2 for 10K vocab |
# | Clean data reaches lower loss | Same compute, better result |
# | Corrupted data produces incoherent text | Side-by-side generation |
# | Cosine LR + warmup is standard | Used in GPT-2, LLaMA, etc. |
#
# ### Artifacts in `outputs/`
#
# | File | What it shows |
# |------|---------------|
# | `05-loss-curves.png` | Clean vs corrupted training curves |
# | `05-training-dynamics.png` | LR schedule and loss distribution |
# | `05-model-clean.pt` | Your trained clean-data model |
# | `05-model-corrupted.pt` | Your trained corrupted-data model |
#
# ### References
#
# - Eldan & Li, "TinyStories" (2023, Microsoft Research)
# - Gunasekar et al., "Textbooks Are All You Need" (2023)
# - Radford et al., "Language Models are Unsupervised Multitask Learners"
#   (GPT-2, 2019)
